<?xml version='1.0' standalone='yes' ?>
<!DOCTYPE librarians [
<!ELEMENT librarians (librarian+)>
<!--The id attribute is used to differentiate the librarians easily--> 
<!ATTLIST librarian id CDATA #REQUIRED>
<!--The elements of each librarian entry are fairly intuitive. There is the possibility of having multiple phone numbers but all the others can only be singular as illustrated by the occurances-->
<!ELEMENT librarian (librarian.name, librarian.phoneNo+, librarian.address, librarian.dateOfBirth, librarian.startDate, librarian.PPSNumber)>
<!--This attribute describes the title of the librarian's name and is a required field and makes use of the logical operation which mean it is a choice-->
<!ENTITY mr "MR">
<!ENTITY ms "MS">
<!ELEMENT librarian.name (#PCDATA)>
<!ATTLIST librarian.name title ( MR |MS) #REQUIRED>
<!ELEMENT librarian.phoneNo (#PCDATA)>
<!--This attribute describes the type of phone number the librarian has provided and is a required field-->
<!ATTLIST librarian.phoneNo type CDATA #REQUIRED>
<!ELEMENT librarian.address (#PCDATA)>
<!ELEMENT librarian.dateOfBirth (#PCDATA)>
<!ELEMENT librarian.startDate (#PCDATA)>
<!ELEMENT librarian.PPSNumber (#PCDATA)>
<!--A PPS number is a required field to ensure the librarian is a c-->
<!ATTLIST librarian.PPSNumber verified CDATA #REQUIRED>

]>

<librarians>
    <librarian id="001">
       <librarian.name title="&ms;">Eileen Foley</librarian.name>
	   <librarian.phoneNo type ="Mobile">0871234567</librarian.phoneNo>
	   <librarian.phoneNo type ="Home">01476308925</librarian.phoneNo>
	   <librarian.address>17 yellow lane, rathfarnham, Dublin</librarian.address>
	   <librarian.dateOfBirth>1950-12-07</librarian.dateOfBirth>
	   <librarian.startDate>2000-01-01</librarian.startDate>
	   <librarian.PPSNumber verified="true">738614794T</librarian.PPSNumber>
	</librarian>
	
	<librarian id="002" >
       <librarian.name title="&ms;">Gwyneth Richardson</librarian.name>
	   <librarian.phoneNo type="Mobile">0877654321</librarian.phoneNo>
	   <librarian.address>the Nook, Bray, Co. Wicklow</librarian.address>
	   <librarian.dateOfBirth>19/07/1958</librarian.dateOfBirth>
	   <librarian.startDate>2014-04-07</librarian.startDate>
	   <librarian.PPSNumber verified="true">279254794P</librarian.PPSNumber>
	</librarian>
	
	<librarian id="003" >
       <librarian.name title="&ms;">Lauren Duffy</librarian.name>
	   <librarian.phoneNo type="Mobile">0877654321</librarian.phoneNo>
	   <librarian.address>Dundrum, Co. Dublin</librarian.address>
	   <librarian.dateOfBirth>1948-11-18</librarian.dateOfBirth>
	   <librarian.startDate>1978-11-18</librarian.startDate>
	   <librarian.PPSNumber verified="true">1489150185P</librarian.PPSNumber>
	</librarian>
</librarians>

