<?xml version='1.0' standalone='yes' ?>
<!DOCTYPE locations [
<!--States the name of the entries in the locations class-->
<!ELEMENT locations (location+)>
<!--the location ID allows us to refer to a location very easily in outside xml classes-->
<!ATTLIST location id CDATA #REQUIRED>
<!-- all occurances are singular except material Id as you can get multiple materials out at one time-->
<!ELEMENT location (location.name, location.bookedBy, location.bookedFor, location.bookingTime, location.bookingDate, location.bookingNotes, location.materialID+)>
<!ENTITY reading_room1 "READINGROOM1">
<!ENTITY reading_room2 "READINGROOM2">
<!ENTITY reading_room3 "READINGROOM3">
<!--logial choice of reading rooms. Can only choose the one-->
<!ELEMENT location.name (#PCDATA | readingRoom1 | readingRoom2 | readingRoom3 )*>
<!ELEMENT location.bookedBy (#PCDATA)>
<!--the bookedBy ID allows us to refer to a librarian very easily in this xml class-->
<!ATTLIST location.bookedBy id CDATA #REQUIRED>
<!ELEMENT location.bookedFor (#PCDATA)>
<!--the bookedFor ID allows us to refer to a patron very easily in this xml class-->
<!ATTLIST location.bookedFor id CDATA #REQUIRED>
<!ELEMENT location.bookingTime (#PCDATA)>
<!--the booking time zone attribute allows us to clarify which time zone the booking is made for-->
<!ATTLIST location.bookingTime zone CDATA #REQUIRED>
<!ELEMENT location.bookingDate (#PCDATA)>
<!ELEMENT location.bookingNotes (#PCDATA)>
<!ELEMENT location.materialID (#PCDATA)>


]>

<locations>
    <location id="001">
       <location.name>&reading_room1;</location.name>
	   <location.bookedBy id="001">Eileen</location.bookedBy>
	   <location.bookedFor id="001">Colman Kinane</location.bookedFor>
	   <location.bookingTime zone ="UTC +0">13:00</location.bookingTime>
	   <location.bookingDate>2017-09-12</location.bookingDate>
	   <location.bookingNotes>Nothing to Note</location.bookingNotes>
	   <location.materialID>004</location.materialID>
	</location>
	
	<location id="001">
       <location.name>&reading_room2;</location.name>
	   <location.bookedBy id="002">Gwyneth</location.bookedBy>
	   <location.bookedFor id="002">Jack Donal Collins</location.bookedFor>
	   <location.bookingTime zone ="UTC +0">13:00</location.bookingTime>
	   <location.bookingDate>2017-09-12</location.bookingDate>
	   <location.bookingNotes>Nothing to Note</location.bookingNotes>
	   <location.materialID>002</location.materialID>
	   <location.materialID>003</location.materialID>
	   <location.materialID>010</location.materialID>
	</location>
</locations>

