<?xml version='1.0' standalone='yes' ?>
<!DOCTYPE readerTickets [
<!ELEMENT readerTickets (readerTicket*)>
<!--the readerticket ID allows us to refer to a readerticket very easily in outside xml classes-->
<!ATTLIST readerTicket id CDATA #REQUIRED>
<!--The permission level of a patron to see certain materials-->
<!ATTLIST readerTicket permLevel CDATA #REQUIRED>
<!--Information about the patron that is held in the readerticket such as name and DOB-->
<!ELEMENT readerTicket (readerTicket.name, readerTicket.dateOfBirth, readerTicket.photographicID, readerTicket.issueDate, readerTicket.expiryDate, readerTicket.address*)>
<!--The components of readerticket.naem is made up of title, first name and second name-->
<!ELEMENT readerTicket.name (readerTicket.firstName,readerTicket.surname)>
<!ATTLIST readerTicket.name title ( MR | MS ) #REQUIRED>
<!ENTITY mr "MR">
<!ENTITY ms "MS">
<!ELEMENT readerTicket.title ( #PCDATA | mr | ms )*>
<!ELEMENT readerTicket.firstName (#PCDATA)>
<!ELEMENT readerTicket.surname (#PCDATA)>
<!--DOB is a required attribute for the readerticket class-->
<!ATTLIST readerTicket.dateOfBirth source CDATA #REQUIRED>
<!ELEMENT readerTicket.dateOfBirth (#PCDATA)>
<!ELEMENT readerTicket.photographicID (#PCDATA)>
<!--photographicID is a required attribute for the readerticket class-->
<!ATTLIST readerTicket.photographicID source CDATA #REQUIRED>
<!ELEMENT readerTicket.issueDate (#PCDATA)>
<!ELEMENT readerTicket.expiryDate (#PCDATA)>
<!ELEMENT readerTicket.address (#PCDATA)>
<!--Address is a required attribute for the readerticket class-->
<!ATTLIST readerTicket.address source CDATA #REQUIRED>

]>
<readerTickets>
    <readerTicket id = "001" permLevel="1" >
        <readerTicket.name title="&mr;">
			<readerTicket.firstName>Colman</readerTicket.firstName>
			<readerTicket.surname>Kinane</readerTicket.surname>
		</readerTicket.name>
        <readerTicket.dateOfBirth source="passport">1997-07-11</readerTicket.dateOfBirth>
        <readerTicket.photographicID source="passport">https://someImageAddress.com</readerTicket.photographicID>
        <readerTicket.issueDate>2017-12-06</readerTicket.issueDate>
        <readerTicket.expiryDate>2020-12-06</readerTicket.expiryDate>
        <readerTicket.address source="Utility Bill">15 Carysfort Woods, Blackrock, Co. Dublin</readerTicket.address>
    </readerTicket>
    
    <readerTicket id = "002" permLevel="1">
        <readerTicket.name title="&mr;">
			<readerTicket.firstName>Jack Donal</readerTicket.firstName>
			<readerTicket.surname>Collins</readerTicket.surname>
		</readerTicket.name>
        <readerTicket.dateOfBirth source="passport">1997-11-11</readerTicket.dateOfBirth>
        <readerTicket.photographicID source="passport">https://someImageAddress.com</readerTicket.photographicID>
        <readerTicket.issueDate>2017-12-06</readerTicket.issueDate>
        <readerTicket.expiryDate>2020-12-06</readerTicket.expiryDate>
        <readerTicket.address source="Utility Bill">15 Carysfort Woods, Blackrock, Co. Dublin</readerTicket.address>
    </readerTicket>
    
        <readerTicket id = "003" permLevel="1">
        <readerTicket.name title="&mr;">
			<readerTicket.firstName>Sharon</readerTicket.firstName>
			<readerTicket.surname>Olorunniwo</readerTicket.surname>
		</readerTicket.name>
        <readerTicket.dateOfBirth source="passport">1998-10-19</readerTicket.dateOfBirth>
        <readerTicket.photographicID source="passport">https://someImageAddress.com</readerTicket.photographicID>
        <readerTicket.issueDate>2013-12-06</readerTicket.issueDate>
        <readerTicket.expiryDate>2016-12-06</readerTicket.expiryDate>
        <readerTicket.address source="Utility Bill">Rainbow Road, Rainbow Lane, Dublin</readerTicket.address>
    </readerTicket>
    
     <readerTicket id = "004" permLevel="1">
        <readerTicket.name title="&mr;">
			<readerTicket.firstName>Sinead</readerTicket.firstName>
			<readerTicket.surname>McAleer</readerTicket.surname>
		</readerTicket.name>
        <readerTicket.dateOfBirth source="Public services card">1998-10-19</readerTicket.dateOfBirth>
        <readerTicket.photographicID source="Public services card">https://someImageAddress.com</readerTicket.photographicID>
        <readerTicket.issueDate>2013-12-06</readerTicket.issueDate>
        <readerTicket.expiryDate>2016-12-06</readerTicket.expiryDate>
        <readerTicket.address source="Utility Bill">Rainbow Road, Rainbow Lane, Dublin</readerTicket.address>
    </readerTicket>
      <readerTicket id = "005" permLevel="1">
        <readerTicket.name title="&mr;">
			<readerTicket.firstName>William</readerTicket.firstName>
			<readerTicket.surname>Harty</readerTicket.surname>
		</readerTicket.name>
        <readerTicket.dateOfBirth source="Public services card">1997-03-21</readerTicket.dateOfBirth>
        <readerTicket.photographicID source="Public services card">https://someImageAddress.com</readerTicket.photographicID>
        <readerTicket.issueDate>2013-12-06</readerTicket.issueDate>
        <readerTicket.expiryDate>2016-12-06</readerTicket.expiryDate>
        <readerTicket.address source="Utility Bill">Rainbow Road, Rainbow Lane, Dublin</readerTicket.address>
    </readerTicket>
 
</readerTickets>

